name: PHP

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Validate composer.json and composer.lock
        run: composer validate

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v2
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      - name: Install dependencies
        if: steps.composer-cache.outputs.cache-hit != 'true'
        run: composer install --prefer-dist --no-progress --no-suggest

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: code-sniffer-psr2
        uses: pipeline-components/php-codesniffer@v0.12.3
        with:
          options: -s -p --colors --extensions=php --standard=PSR2 .

      - name: code-sniffer-php72
        uses: pipeline-components/php-codesniffer@v0.12.3
        with:
          options: -s -p --colors --standard=PHPCompatibility --extensions=php --runtime-set testVersion 7.2- .

      - name: code-sniffer-php73
        uses: pipeline-components/php-codesniffer@v0.12.3
        with:
          options: -s -p --colors --standard=PHPCompatibility --extensions=php --runtime-set testVersion 7.3- .

      - name: code-sniffer-php74
        uses: pipeline-components/php-codesniffer@v0.12.3
        with:
          options: -s -p --colors --standard=PHPCompatibility --extensions=php --runtime-set testVersion 7.2- .

      - name: code-sniffer-php80
        uses: pipeline-components/php-codesniffer@v0.12.3
        with:
          options: -s -p --colors --standard=PHPCompatibility --extensions=php --runtime-set testVersion 8.0- .
