name: PHP

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Validate composer.json and composer.lock
        run: composer validate

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v2
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      - name: Install dependencies
        if: steps.composer-cache.outputs.cache-hit != 'true'
        run: composer install --prefer-dist --no-progress --no-suggest

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: PSR2 Code style test
        uses: pipelinecomponents/php-codesniffer:latest
        run: phpcs -s -p --colors --extensions=php --standard=PSR2 .

      - name: PSR2 Code style test
        run: >-
          phpcs -s -p --colors
          --standard=PHPCompatibility
          --extensions=php
          --runtime-set testVersion 7.2 .
#        run: phpcs -s -p --colors --extensions=php --standard=PSR2 .
